import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  User,
  Team,
  Match,
  MatchResult,
  Prediction,
  UserScore,
  NewsArticle,
} from '../entities';
import {
  UserRepository,
  TeamRepository,
  MatchRepository,
  MatchResultRepository,
  PredictionRepository,
  UserScoreRepository,
  NewsArticleRepository,
} from '../repositories';
import {
  UserService,
  TeamService,
  MatchService,
  MatchResultService,
  PredictionService,
  UserScoreService,
  NewsArticleService,
  ScoringService,
  LockdownService,
  TimezoneService,
} from '../services';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      Team,
      Match,
      MatchResult,
      Prediction,
      UserScore,
      NewsArticle,
    ]),
  ],
  providers: [
    UserRepository,
    TeamRepository,
    MatchRepository,
    MatchResultRepository,
    PredictionRepository,
    UserScoreRepository,
    NewsArticleRepository,
    UserService,
    TeamService,
    MatchService,
    MatchResultService,
    PredictionService,
    UserScoreService,
    NewsArticleService,
    ScoringService,
    LockdownService,
    TimezoneService,
  ],
  exports: [
    UserRepository,
    TeamRepository,
    MatchRepository,
    MatchResultRepository,
    PredictionRepository,
    UserScoreRepository,
    NewsArticleRepository,
    UserService,
    TeamService,
    MatchService,
    MatchResultService,
    PredictionService,
    UserScoreService,
    NewsArticleService,
    ScoringService,
    LockdownService,
    TimezoneService,
  ],
})
export class DataAccessModule {}
